[project]
name = "papa"
version = "0.0.1"
description = "Papa: Amazing Python Analytics"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "nltk>=3.9.1",
    "pandas>=2.3.1",
    "pip>=25.1.1",
    "spacy>=3.8.7",
]
